name: Build and Release Funser

on:
  push:
    tags:
      - 'v*' # Se activa al subir un tag (ej. v1.0.0)
  workflow_dispatch: # ESTO ACTIVA EL BOTÓN PARA LANZARLO MANUALMENTE

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar MinGW x64
        uses: egor-tensin/setup-mingw@v3
        with:
          platform: x64

      - name: Compilar
        run: |
          gcc src/main.c include/mujs/one.c "include/raylib/raylib-6.0_win64_mingw-w64/lib/libraylib.a" -o funser.exe -I"include/raylib/raylib-6.0_win64_mingw-w64/include" -I"include/mujs" -lopengl32 -lgdi32 -lwinmm

      - name: Preparar nombre del archivo
        shell: bash
        run: |
          # Si se lanza manualmente, github.ref_name será 'main', si es por tag será 'v1.0.0'
          mv funser.exe "funser-${{ github.ref_name }}-win64.exe"

      - name: Subir a GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: funser-*-win64.exe
          generate_release_notes: true
          fail_on_unresolved_object: false # Evita errores si el tag es confuso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
